let constant = {
    TRUE: true,
    FALSE: false,
    TRUEMSG: 'Successful',
    FALSEMSG: 'Please try again later',
    SENTMSG: 'Sent successfully',
    REGISTERMSG: 'Sent successfully',
    INVALIDPARAMS: 'Invalid parameters',
    NOTREGISTERED: 'This email not registered with any account',
    EXISTSMSG: 'associated with another account',
    SOMETHINGWRONG: 'Something went wrong. Please try again later',
    ADDMSG: 'Added successfully',
    UPDATEMSG: 'Updated sucessfully',
    SAVEMSG: 'Saved sucessfully',
    DELETEMSG: 'Deleted sucessfully',
    NOFILEMSG: 'No file selected',
    REGISTERAPP: 'You have successfully registered for this app',
    GROUPCREATESUCCESS: 'Group has been created succesffuly',
    EXISTSMSG: 'associated with another account(Account already taken, try another)',
    PARAMSMISSING: 'Parameters Missing',
    CONVOMISSING: 'Conversation ID Missing',
    OPPOMISSING: 'opponent ID Missing',
    MESSAGEDELETE: 'please provide array of message IDs to be deleted',
    PARAMSGROUPMISSING: `Provide group ID`,
    OBJECTIDERROR: 'Provide valid user ObjectIDs',
    GROUPUSERMISSING: 'Either groupId or userId is missing',
    GROUPUSERADMINMISSING: 'one of groupId or adminId  userId is missing',
    PARAMSMISSINGCHATHISTORY: 'Provide both sender and reciever Id',
    PARAMSMISSINGGROUPCHATHISTORY: 'Provide sender Id',
    BLOCKMESSAGE: 'You cannot send mesage.You are blocked by the user',
    NOTFOLLOWING: 'Sorry you cant send message. Person doesnt follow you',
    ALREADYBLOCKED: 'User is already blocked',
    UNBLOCKED: 'User is unblocked succesfully',
    BLOCKED: 'User is blocked Successfully',
    FILEMISSING: 'Missing File',
    CLEARED: 'CLeared',

    // Uploaded 
    USERIMAGE: 'static/users/',
    MESSAGEMEDIA: 'static/media/',

    // URL
    BASEURL: 'http://13.232.208.65:9000/',
}

module.exports = constant